apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-test-build-push-hi-cache
  namespace: devops
spec:
  resources:
    - name: code-repo
      type: git
  tasks:  # 定义任务
    - name: step-test
      taskRef:
        name: go-test-task
      resources:
        inputs:
          - name: repo # /workspace/repo
            resource: code-repo
    - name: build-and-push
      taskRef:
        name: build-and-push-hi-cache
      runAfter:
        - step-test   # 测试任务执行之后再执行
      resources:
        inputs:
          - name: repo
            resource: code-repo