apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-hi-cache  # 构建和推送
  namespace: devops
spec:
  resources:
    inputs:
      - name: repo   # 名称
        type: git   # 类型 git、pullRequest、image、cluster...
  steps:
    - name: build-and-push
      image: cnych/kaniko-executor:v0.22.0
      env:
        - name: DOCKER_CONFIG   # 用于kaniko去查找docker的认证信息
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
        - --dockerfile=Dockerfile
        - --context=/workspace/repo
        - --destination=miyaweb/hihttp:v2
        - --cache=true
#        - --cache-dir=/image-cache
#      volumeMounts:
#        - name: image-cache
#          mountPath: /image-cache

#https://www.yisu.com/zixun/566637.html