apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-test-task
  namespace: devops
spec:
  resources:
    inputs:
      - name: repo #/workspace/repo
        type: git
  steps:
    - name: run-go-test
      image: golang:1.14
      workingDir: /workspace/repo
      command: [ "go" ]
      args: [ "test", "-v" ]
